project_name: jarrett-yq
version: 2
dist: build

builds:
  - id: yq

    binary: yq_{{ .Os }}_{{ .Arch }}

    ldflags:
      - -s -w

    env:
      - CGO_ENABLED=0

    targets:
      - linux_arm64

    no_unique_dist_dir: true

release:
  github:
    owner: jarrettgaither
    name: yq
