on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  go-release:
    runs-on: self-hosted
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --rm-dist --snapshot
